name: MinecartMayhem
version: '1.0-SNAPSHOT'
main: io.github.sbisel126.minecartMayhem.MinecartMayhem
api-version: '1.21'
commands:
  teleport_menu:
    description: Opens the map selection menu. DEVELOPMENT USE
    usage: /teleport_menu
    aliases: teleport
    permission: teleport_menu
    permission-message: You do not have permission to open the map menu.
  cart_menu:
    description: Opens the cart selection menu.
    usage: /cart_menu
    aliases: cart
    permission: cart_menu
    permission-message: You do not have permission to open the cart menu.
  join_race:
    description: Starts the race clock.
    usage: /join_race
    aliases: race
    permission: join_race
    permission-message: You do not have permission to join a race.
  debug_command:
    description: debug
    usage: /debug_command
    aliases: debug
    permission: debug
    permission-message: no.
  itemboxwand:
      description: Gives you the item box wand
